import { BadRequestException, Body, Controller, Headers, Post } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { z } from 'zod';
import { SupabaseService } from './supabase.service.js';

const startSchema=z.object({workspaceId:z.uuid(),releaseId:z.uuid(),name:z.string().min(1).max(160),fileName:z.string().regex(/^[a-zA-Z0-9._-]+$/),mimeType:z.enum(['image/png','image/jpeg','image/webp']),byteSize:z.number().int().min(1).max(20*1024*1024)});
@ApiTags('artifacts') @ApiBearerAuth() @Controller('artifacts')
export class ArtifactsController{
  constructor(private readonly db:SupabaseService){}
  @Post('uploads') async start(@Headers('authorization') authorization:string|undefined,@Body() input:unknown){const body=startSchema.parse(input);const {client,user}=await this.db.authenticated(authorization);const {data:artifact,error}=await client.from('artifacts').insert({workspace_id:body.workspaceId,release_id:body.releaseId,name:body.name,created_by:user.id}).select('id').single();this.db.unwrap(artifact,error);const path=`${body.workspaceId}/${body.releaseId}/${artifact!.id}/1/${body.fileName}`;const {data:signed,error:signError}=await client.storage.from('release-artifacts').createSignedUploadUrl(path);if(signError)throw new BadRequestException(signError.message);return {artifactId:artifact!.id,path,token:signed.token,signedUrl:signed.signedUrl};}
  @Post('uploads/complete') async complete(@Headers('authorization') authorization:string|undefined,@Body() input:unknown){const body=z.object({workspaceId:z.uuid(),artifactId:z.uuid(),path:z.string().min(10),mimeType:z.enum(['image/png','image/jpeg','image/webp']),byteSize:z.number().int().min(1).max(20*1024*1024),width:z.number().int().positive(),height:z.number().int().positive()}).parse(input);const {client,user}=await this.db.authenticated(authorization);if(!body.path.startsWith(`${body.workspaceId}/`))throw new BadRequestException('Storage path does not belong to the workspace');const folder=body.path.slice(0,body.path.lastIndexOf('/'));const fileName=body.path.slice(body.path.lastIndexOf('/')+1);const {data:objects,error:listError}=await client.storage.from('release-artifacts').list(folder,{search:fileName,limit:2});if(listError||!objects?.some(object=>object.name===fileName))throw new BadRequestException('Uploaded object was not found');const {data,error}=await client.from('artifact_versions').insert({workspace_id:body.workspaceId,artifact_id:body.artifactId,version:1,storage_path:body.path,mime_type:body.mimeType,byte_size:body.byteSize,width:body.width,height:body.height,uploaded_by:user.id}).select().single();return this.db.unwrap(data,error);}
}
