import { BadRequestException, Body, Controller, Get, Headers, Param, Patch, Post, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { randomBytes } from 'node:crypto';
import { createHash } from 'node:crypto';
import { z } from 'zod';
import { SupabaseService } from './supabase.service.js';

@ApiTags('review') @ApiBearerAuth() @Controller()
export class ReviewController{
  constructor(private readonly db:SupabaseService){}
  @Get('checklists') async checklist(@Headers('authorization') authorization:string|undefined,@Query('releaseId') releaseId:string){const {client}=await this.db.authenticated(authorization);const {data,error}=await client.from('checklist_items').select().eq('release_id',releaseId).order('position');return this.db.unwrap(data,error);}
  @Post('checklists') async addChecklist(@Headers('authorization') authorization:string|undefined,@Body() input:unknown){const body=z.object({workspaceId:z.uuid(),releaseId:z.uuid(),label:z.string().min(2).max(240),position:z.number().int().min(0)}).parse(input);const {client}=await this.db.authenticated(authorization);const {data,error}=await client.from('checklist_items').insert({workspace_id:body.workspaceId,release_id:body.releaseId,label:body.label,position:body.position}).select().single();return this.db.unwrap(data,error);}
  @Patch('checklists/:id') async toggleChecklist(@Headers('authorization') authorization:string|undefined,@Param('id') id:string,@Body() input:unknown){const body=z.object({completed:z.boolean()}).parse(input);const {client,user}=await this.db.authenticated(authorization);const {data,error}=await client.from('checklist_items').update({completed_at:body.completed?new Date().toISOString():null,completed_by:body.completed?user.id:null}).eq('id',id).select().single();return this.db.unwrap(data,error);}
  @Post('share-links') async createShare(@Headers('authorization') authorization:string|undefined,@Body() input:unknown){const body=z.object({workspaceId:z.uuid(),releaseId:z.uuid()}).parse(input);const {client,user}=await this.db.authenticated(authorization);const token=randomBytes(32).toString('base64url');const tokenHash=createHash('sha256').update(token).digest('hex');const expiresAt=new Date(Date.now()+30*86400000).toISOString();const {data,error}=await client.from('share_links').insert({workspace_id:body.workspaceId,release_id:body.releaseId,token_hash:tokenHash,expires_at:expiresAt,created_by:user.id}).select('id,expires_at').single();return {...this.db.unwrap(data,error),token};}
  @Post('approvals') async decide(@Headers('authorization') authorization:string|undefined,@Body() input:unknown){const body=z.object({workspaceId:z.uuid(),releaseId:z.uuid(),decision:z.enum(['approved','changes_requested']),note:z.string().max(2000).optional(),idempotencyKey:z.string().min(8).max(120)}).parse(input);const {client,user}=await this.db.authenticated(authorization);const {data:release,error:releaseError}=await client.from('releases').select('status').eq('id',body.releaseId).single();this.db.unwrap(release,releaseError);if(release?.status!=='in_review')throw new BadRequestException('Release is not awaiting a decision');const {data:latest}=await client.from('approval_requests').select('review_cycle').eq('release_id',body.releaseId).order('review_cycle',{ascending:false}).limit(1).maybeSingle();const cycle=(latest?.review_cycle??0)+1;const {data:request,error:reqError}=await client.from('approval_requests').insert({workspace_id:body.workspaceId,release_id:body.releaseId,review_cycle:cycle,requested_by:user.id,closed_at:new Date().toISOString()}).select('id').single();this.db.unwrap(request,reqError);const {data,error}=await client.from('approval_decisions').insert({workspace_id:body.workspaceId,approval_request_id:request!.id,decision:body.decision,reviewer_user_id:user.id,note:body.note??null,idempotency_key:body.idempotencyKey}).select().single();return this.db.unwrap(data,error);}
}
